//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Main/Scripts/Content/MainContent/UserIO/UserInputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UserInputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UserInputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UserInputSystem"",
    ""maps"": [
        {
            ""name"": ""RTSCamera"",
            ""id"": ""b3983951-437a-4a8a-ab07-27fed8b429c1"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""c4daee07-a6bb-4833-9f67-a4b7963d91a9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""2360456a-a6ce-42b5-b8f7-c0583877c247"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""8d9cdb61-7b8d-40bf-bf83-b3056916f55c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseMove"",
                    ""type"": ""Value"",
                    ""id"": ""5e9f40ed-dc83-4e5f-94ae-9e0eac60ed83"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseZoom"",
                    ""type"": ""Value"",
                    ""id"": ""0f3eff81-fdbf-48e0-ba13-0cc42106d771"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""c0cba257-b53a-4752-a9cd-130bf78ff276"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""946157d4-af08-46a1-b49d-228d915a6abf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""973c81f8-f037-4f08-b805-772a56d22ceb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""66f8de10-041b-4102-9092-9ffc3a0f602e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""08776c8f-377a-473b-88dd-04ecc8193050"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""KeyArrow"",
                    ""id"": ""876803f9-b093-4569-b2e5-74a804618537"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bdba3d9d-8b13-4ae0-a167-8f199bf9050f"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""57a531d2-df78-432c-a680-e2b9577131b0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""83ff5a62-f625-4a96-a1c9-e7b082a005b8"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f8b21473-03c3-475f-bddc-67b9cdc17338"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Distance"",
                    ""id"": ""fbf2e3d6-66e0-4295-be93-912f3c1318ed"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""ed80e9ab-48b6-417d-8dc3-8eaee9f48f9e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""98aa6194-9fef-4b1a-9bfd-320413523dc8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""15516822-9fb5-40e7-8474-f2171443b27d"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b7be727-6854-443a-be3f-5c84a3bc601b"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""ca72b054-9f5f-43f9-935f-6e2ec415cb70"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7fe98d1e-c245-4867-b0c6-1e54812ab4d3"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""96576e65-8010-4338-bfb6-2d06c5adfb43"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Selection"",
            ""id"": ""dac0d88e-7b15-49b0-801f-cf1e648610df"",
            ""actions"": [
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""8aa9c802-7357-4faf-a7e5-8671da16c577"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""3d521280-3d96-493e-9d30-a7f924a9144d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""24d0c959-b2ee-4323-9abf-04ce891a78e8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Include"",
                    ""type"": ""Button"",
                    ""id"": ""9e5c5c33-e7ff-46f2-98c5-1b9aa2f56e77"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exclude"",
                    ""type"": ""Button"",
                    ""id"": ""e83b67d0-9dee-426b-8e9a-4d0515cacdd5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InvertSelect"",
                    ""type"": ""Button"",
                    ""id"": ""52f6f9ae-00a4-4b6b-8c53-6fddd669d39d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5820b02d-40b3-451c-a66a-503c66e7c07b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e997a34-d5ef-47d8-a643-1817721df886"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f32ab1b-8330-4fe5-9687-bac3d51503f5"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Include"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6507b22-1840-46ad-9355-19522b81ba9c"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exclude"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dacebaeb-3787-457c-a64c-dc0480df2637"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f54133ac-dfd9-4fc1-99e5-95fba7f73c32"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InvertSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Number"",
            ""id"": ""8aed89ca-23d0-4f79-97f4-39cb035e9df3"",
            ""actions"": [
                {
                    ""name"": ""1"",
                    ""type"": ""Button"",
                    ""id"": ""aa984141-8521-4476-82be-529532cc848b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2"",
                    ""type"": ""Button"",
                    ""id"": ""808d9ec4-ddc8-458b-a043-d9c243f0cb40"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3"",
                    ""type"": ""Button"",
                    ""id"": ""4ace906d-31d9-4fb5-8449-bdba583a9926"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""4"",
                    ""type"": ""Button"",
                    ""id"": ""35350a1e-d47e-41ff-8e3f-41acfcecc7bf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""5"",
                    ""type"": ""Button"",
                    ""id"": ""dea259d9-e729-4ee5-b67a-9d479556fe17"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""6"",
                    ""type"": ""Button"",
                    ""id"": ""ef55bf87-f592-4ac0-a4cb-6aeac49dd07f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""7"",
                    ""type"": ""Button"",
                    ""id"": ""16468bd5-9243-49e8-9c29-587cfb50554f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""8"",
                    ""type"": ""Button"",
                    ""id"": ""a5d99e8b-9804-42c8-8abd-ef134cc1461e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""9"",
                    ""type"": ""Button"",
                    ""id"": ""4709b688-cb3d-4963-9aa6-9d989cb29de1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""0"",
                    ""type"": ""Button"",
                    ""id"": ""3f79fde2-7c83-4463-824d-392dab210a08"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2c746923-385c-4eea-93db-2309e21f4b4e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93376e88-d616-431b-9978-24c0f7749e52"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae85aadf-c328-4579-b35e-77ffea41d8a8"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""627c9472-94b4-4095-8c2b-dba7c9d12355"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cde8ddb1-23ce-44fe-954e-86a122f5f119"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae765313-a9a4-45ed-9bb3-e4fa1b0d4ed9"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ed63104-a324-4a2a-94bd-57e77b55a6bc"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b38aa95-170c-419a-a216-f3dac14ec745"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcb064d0-0925-4d42-b4d1-9bfb5b1e4c39"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a66502c4-504e-4e0d-a9a8-bb24036b7f54"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9c8733e-21ff-42cb-a191-b9c4ec39899e"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa706634-b666-4360-ad79-1c52c0fdef3c"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd16d169-b2eb-4011-9ec3-5d84e82bc499"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6d581ed-30cd-4af4-8fb8-6b2f1b8352e4"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""285933b5-286b-415d-9f08-d046c0f599df"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb64c582-7395-4098-8e83-961c18add99a"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eea92f65-c0cc-4681-ba84-16d470af1272"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""beaee8b9-60f0-469e-b6b3-746fbe6994a5"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b9bff72-bfb7-4c31-89ca-ddc49bb35ce8"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9c39b04-369c-41dc-883a-0432d34eed62"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Command"",
            ""id"": ""f7e83067-59e8-4f57-8746-3132da85cab4"",
            ""actions"": [
                {
                    ""name"": ""OpenActionPalette"",
                    ""type"": ""Button"",
                    ""id"": ""f205ab51-f7a7-4617-a4df-351a6b7d0ad4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a969c64e-8a81-42e5-bda6-6a0bc8d219d3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenActionPalette"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ActionPalette"",
            ""id"": ""6895cb84-5c69-4270-a956-5ce5c3397b3a"",
            ""actions"": [
                {
                    ""name"": ""ClosePalette"",
                    ""type"": ""Button"",
                    ""id"": ""1a32c791-b9a9-421d-a09f-3c6dc8db4e15"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7f0c07c4-f790-461b-a81e-52231e10a041"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClosePalette"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RTSCamera
        m_RTSCamera = asset.FindActionMap("RTSCamera", throwIfNotFound: true);
        m_RTSCamera_Move = m_RTSCamera.FindAction("Move", throwIfNotFound: true);
        m_RTSCamera_Rotate = m_RTSCamera.FindAction("Rotate", throwIfNotFound: true);
        m_RTSCamera_Zoom = m_RTSCamera.FindAction("Zoom", throwIfNotFound: true);
        m_RTSCamera_MouseMove = m_RTSCamera.FindAction("MouseMove", throwIfNotFound: true);
        m_RTSCamera_MouseZoom = m_RTSCamera.FindAction("MouseZoom", throwIfNotFound: true);
        // Selection
        m_Selection = asset.FindActionMap("Selection", throwIfNotFound: true);
        m_Selection_MousePos = m_Selection.FindAction("MousePos", throwIfNotFound: true);
        m_Selection_Select = m_Selection.FindAction("Select", throwIfNotFound: true);
        m_Selection_Cancel = m_Selection.FindAction("Cancel", throwIfNotFound: true);
        m_Selection_Include = m_Selection.FindAction("Include", throwIfNotFound: true);
        m_Selection_Exclude = m_Selection.FindAction("Exclude", throwIfNotFound: true);
        m_Selection_InvertSelect = m_Selection.FindAction("InvertSelect", throwIfNotFound: true);
        // Number
        m_Number = asset.FindActionMap("Number", throwIfNotFound: true);
        m_Number__1 = m_Number.FindAction("1", throwIfNotFound: true);
        m_Number__2 = m_Number.FindAction("2", throwIfNotFound: true);
        m_Number__3 = m_Number.FindAction("3", throwIfNotFound: true);
        m_Number__4 = m_Number.FindAction("4", throwIfNotFound: true);
        m_Number__5 = m_Number.FindAction("5", throwIfNotFound: true);
        m_Number__6 = m_Number.FindAction("6", throwIfNotFound: true);
        m_Number__7 = m_Number.FindAction("7", throwIfNotFound: true);
        m_Number__8 = m_Number.FindAction("8", throwIfNotFound: true);
        m_Number__9 = m_Number.FindAction("9", throwIfNotFound: true);
        m_Number__0 = m_Number.FindAction("0", throwIfNotFound: true);
        // Command
        m_Command = asset.FindActionMap("Command", throwIfNotFound: true);
        m_Command_OpenActionPalette = m_Command.FindAction("OpenActionPalette", throwIfNotFound: true);
        // ActionPalette
        m_ActionPalette = asset.FindActionMap("ActionPalette", throwIfNotFound: true);
        m_ActionPalette_ClosePalette = m_ActionPalette.FindAction("ClosePalette", throwIfNotFound: true);
    }

    ~@UserInputSystem()
    {
        UnityEngine.Debug.Assert(!m_RTSCamera.enabled, "This will cause a leak and performance issues, UserInputSystem.RTSCamera.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Selection.enabled, "This will cause a leak and performance issues, UserInputSystem.Selection.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Number.enabled, "This will cause a leak and performance issues, UserInputSystem.Number.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Command.enabled, "This will cause a leak and performance issues, UserInputSystem.Command.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_ActionPalette.enabled, "This will cause a leak and performance issues, UserInputSystem.ActionPalette.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RTSCamera
    private readonly InputActionMap m_RTSCamera;
    private List<IRTSCameraActions> m_RTSCameraActionsCallbackInterfaces = new List<IRTSCameraActions>();
    private readonly InputAction m_RTSCamera_Move;
    private readonly InputAction m_RTSCamera_Rotate;
    private readonly InputAction m_RTSCamera_Zoom;
    private readonly InputAction m_RTSCamera_MouseMove;
    private readonly InputAction m_RTSCamera_MouseZoom;
    public struct RTSCameraActions
    {
        private @UserInputSystem m_Wrapper;
        public RTSCameraActions(@UserInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_RTSCamera_Move;
        public InputAction @Rotate => m_Wrapper.m_RTSCamera_Rotate;
        public InputAction @Zoom => m_Wrapper.m_RTSCamera_Zoom;
        public InputAction @MouseMove => m_Wrapper.m_RTSCamera_MouseMove;
        public InputAction @MouseZoom => m_Wrapper.m_RTSCamera_MouseZoom;
        public InputActionMap Get() { return m_Wrapper.m_RTSCamera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RTSCameraActions set) { return set.Get(); }
        public void AddCallbacks(IRTSCameraActions instance)
        {
            if (instance == null || m_Wrapper.m_RTSCameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RTSCameraActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @MouseMove.started += instance.OnMouseMove;
            @MouseMove.performed += instance.OnMouseMove;
            @MouseMove.canceled += instance.OnMouseMove;
            @MouseZoom.started += instance.OnMouseZoom;
            @MouseZoom.performed += instance.OnMouseZoom;
            @MouseZoom.canceled += instance.OnMouseZoom;
        }

        private void UnregisterCallbacks(IRTSCameraActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @MouseMove.started -= instance.OnMouseMove;
            @MouseMove.performed -= instance.OnMouseMove;
            @MouseMove.canceled -= instance.OnMouseMove;
            @MouseZoom.started -= instance.OnMouseZoom;
            @MouseZoom.performed -= instance.OnMouseZoom;
            @MouseZoom.canceled -= instance.OnMouseZoom;
        }

        public void RemoveCallbacks(IRTSCameraActions instance)
        {
            if (m_Wrapper.m_RTSCameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRTSCameraActions instance)
        {
            foreach (var item in m_Wrapper.m_RTSCameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RTSCameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RTSCameraActions @RTSCamera => new RTSCameraActions(this);

    // Selection
    private readonly InputActionMap m_Selection;
    private List<ISelectionActions> m_SelectionActionsCallbackInterfaces = new List<ISelectionActions>();
    private readonly InputAction m_Selection_MousePos;
    private readonly InputAction m_Selection_Select;
    private readonly InputAction m_Selection_Cancel;
    private readonly InputAction m_Selection_Include;
    private readonly InputAction m_Selection_Exclude;
    private readonly InputAction m_Selection_InvertSelect;
    public struct SelectionActions
    {
        private @UserInputSystem m_Wrapper;
        public SelectionActions(@UserInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePos => m_Wrapper.m_Selection_MousePos;
        public InputAction @Select => m_Wrapper.m_Selection_Select;
        public InputAction @Cancel => m_Wrapper.m_Selection_Cancel;
        public InputAction @Include => m_Wrapper.m_Selection_Include;
        public InputAction @Exclude => m_Wrapper.m_Selection_Exclude;
        public InputAction @InvertSelect => m_Wrapper.m_Selection_InvertSelect;
        public InputActionMap Get() { return m_Wrapper.m_Selection; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SelectionActions set) { return set.Get(); }
        public void AddCallbacks(ISelectionActions instance)
        {
            if (instance == null || m_Wrapper.m_SelectionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SelectionActionsCallbackInterfaces.Add(instance);
            @MousePos.started += instance.OnMousePos;
            @MousePos.performed += instance.OnMousePos;
            @MousePos.canceled += instance.OnMousePos;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Include.started += instance.OnInclude;
            @Include.performed += instance.OnInclude;
            @Include.canceled += instance.OnInclude;
            @Exclude.started += instance.OnExclude;
            @Exclude.performed += instance.OnExclude;
            @Exclude.canceled += instance.OnExclude;
            @InvertSelect.started += instance.OnInvertSelect;
            @InvertSelect.performed += instance.OnInvertSelect;
            @InvertSelect.canceled += instance.OnInvertSelect;
        }

        private void UnregisterCallbacks(ISelectionActions instance)
        {
            @MousePos.started -= instance.OnMousePos;
            @MousePos.performed -= instance.OnMousePos;
            @MousePos.canceled -= instance.OnMousePos;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Include.started -= instance.OnInclude;
            @Include.performed -= instance.OnInclude;
            @Include.canceled -= instance.OnInclude;
            @Exclude.started -= instance.OnExclude;
            @Exclude.performed -= instance.OnExclude;
            @Exclude.canceled -= instance.OnExclude;
            @InvertSelect.started -= instance.OnInvertSelect;
            @InvertSelect.performed -= instance.OnInvertSelect;
            @InvertSelect.canceled -= instance.OnInvertSelect;
        }

        public void RemoveCallbacks(ISelectionActions instance)
        {
            if (m_Wrapper.m_SelectionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISelectionActions instance)
        {
            foreach (var item in m_Wrapper.m_SelectionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SelectionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SelectionActions @Selection => new SelectionActions(this);

    // Number
    private readonly InputActionMap m_Number;
    private List<INumberActions> m_NumberActionsCallbackInterfaces = new List<INumberActions>();
    private readonly InputAction m_Number__1;
    private readonly InputAction m_Number__2;
    private readonly InputAction m_Number__3;
    private readonly InputAction m_Number__4;
    private readonly InputAction m_Number__5;
    private readonly InputAction m_Number__6;
    private readonly InputAction m_Number__7;
    private readonly InputAction m_Number__8;
    private readonly InputAction m_Number__9;
    private readonly InputAction m_Number__0;
    public struct NumberActions
    {
        private @UserInputSystem m_Wrapper;
        public NumberActions(@UserInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @_1 => m_Wrapper.m_Number__1;
        public InputAction @_2 => m_Wrapper.m_Number__2;
        public InputAction @_3 => m_Wrapper.m_Number__3;
        public InputAction @_4 => m_Wrapper.m_Number__4;
        public InputAction @_5 => m_Wrapper.m_Number__5;
        public InputAction @_6 => m_Wrapper.m_Number__6;
        public InputAction @_7 => m_Wrapper.m_Number__7;
        public InputAction @_8 => m_Wrapper.m_Number__8;
        public InputAction @_9 => m_Wrapper.m_Number__9;
        public InputAction @_0 => m_Wrapper.m_Number__0;
        public InputActionMap Get() { return m_Wrapper.m_Number; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NumberActions set) { return set.Get(); }
        public void AddCallbacks(INumberActions instance)
        {
            if (instance == null || m_Wrapper.m_NumberActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NumberActionsCallbackInterfaces.Add(instance);
            @_1.started += instance.On_1;
            @_1.performed += instance.On_1;
            @_1.canceled += instance.On_1;
            @_2.started += instance.On_2;
            @_2.performed += instance.On_2;
            @_2.canceled += instance.On_2;
            @_3.started += instance.On_3;
            @_3.performed += instance.On_3;
            @_3.canceled += instance.On_3;
            @_4.started += instance.On_4;
            @_4.performed += instance.On_4;
            @_4.canceled += instance.On_4;
            @_5.started += instance.On_5;
            @_5.performed += instance.On_5;
            @_5.canceled += instance.On_5;
            @_6.started += instance.On_6;
            @_6.performed += instance.On_6;
            @_6.canceled += instance.On_6;
            @_7.started += instance.On_7;
            @_7.performed += instance.On_7;
            @_7.canceled += instance.On_7;
            @_8.started += instance.On_8;
            @_8.performed += instance.On_8;
            @_8.canceled += instance.On_8;
            @_9.started += instance.On_9;
            @_9.performed += instance.On_9;
            @_9.canceled += instance.On_9;
            @_0.started += instance.On_0;
            @_0.performed += instance.On_0;
            @_0.canceled += instance.On_0;
        }

        private void UnregisterCallbacks(INumberActions instance)
        {
            @_1.started -= instance.On_1;
            @_1.performed -= instance.On_1;
            @_1.canceled -= instance.On_1;
            @_2.started -= instance.On_2;
            @_2.performed -= instance.On_2;
            @_2.canceled -= instance.On_2;
            @_3.started -= instance.On_3;
            @_3.performed -= instance.On_3;
            @_3.canceled -= instance.On_3;
            @_4.started -= instance.On_4;
            @_4.performed -= instance.On_4;
            @_4.canceled -= instance.On_4;
            @_5.started -= instance.On_5;
            @_5.performed -= instance.On_5;
            @_5.canceled -= instance.On_5;
            @_6.started -= instance.On_6;
            @_6.performed -= instance.On_6;
            @_6.canceled -= instance.On_6;
            @_7.started -= instance.On_7;
            @_7.performed -= instance.On_7;
            @_7.canceled -= instance.On_7;
            @_8.started -= instance.On_8;
            @_8.performed -= instance.On_8;
            @_8.canceled -= instance.On_8;
            @_9.started -= instance.On_9;
            @_9.performed -= instance.On_9;
            @_9.canceled -= instance.On_9;
            @_0.started -= instance.On_0;
            @_0.performed -= instance.On_0;
            @_0.canceled -= instance.On_0;
        }

        public void RemoveCallbacks(INumberActions instance)
        {
            if (m_Wrapper.m_NumberActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(INumberActions instance)
        {
            foreach (var item in m_Wrapper.m_NumberActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NumberActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public NumberActions @Number => new NumberActions(this);

    // Command
    private readonly InputActionMap m_Command;
    private List<ICommandActions> m_CommandActionsCallbackInterfaces = new List<ICommandActions>();
    private readonly InputAction m_Command_OpenActionPalette;
    public struct CommandActions
    {
        private @UserInputSystem m_Wrapper;
        public CommandActions(@UserInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenActionPalette => m_Wrapper.m_Command_OpenActionPalette;
        public InputActionMap Get() { return m_Wrapper.m_Command; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CommandActions set) { return set.Get(); }
        public void AddCallbacks(ICommandActions instance)
        {
            if (instance == null || m_Wrapper.m_CommandActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CommandActionsCallbackInterfaces.Add(instance);
            @OpenActionPalette.started += instance.OnOpenActionPalette;
            @OpenActionPalette.performed += instance.OnOpenActionPalette;
            @OpenActionPalette.canceled += instance.OnOpenActionPalette;
        }

        private void UnregisterCallbacks(ICommandActions instance)
        {
            @OpenActionPalette.started -= instance.OnOpenActionPalette;
            @OpenActionPalette.performed -= instance.OnOpenActionPalette;
            @OpenActionPalette.canceled -= instance.OnOpenActionPalette;
        }

        public void RemoveCallbacks(ICommandActions instance)
        {
            if (m_Wrapper.m_CommandActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICommandActions instance)
        {
            foreach (var item in m_Wrapper.m_CommandActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CommandActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CommandActions @Command => new CommandActions(this);

    // ActionPalette
    private readonly InputActionMap m_ActionPalette;
    private List<IActionPaletteActions> m_ActionPaletteActionsCallbackInterfaces = new List<IActionPaletteActions>();
    private readonly InputAction m_ActionPalette_ClosePalette;
    public struct ActionPaletteActions
    {
        private @UserInputSystem m_Wrapper;
        public ActionPaletteActions(@UserInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClosePalette => m_Wrapper.m_ActionPalette_ClosePalette;
        public InputActionMap Get() { return m_Wrapper.m_ActionPalette; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActionPaletteActions set) { return set.Get(); }
        public void AddCallbacks(IActionPaletteActions instance)
        {
            if (instance == null || m_Wrapper.m_ActionPaletteActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ActionPaletteActionsCallbackInterfaces.Add(instance);
            @ClosePalette.started += instance.OnClosePalette;
            @ClosePalette.performed += instance.OnClosePalette;
            @ClosePalette.canceled += instance.OnClosePalette;
        }

        private void UnregisterCallbacks(IActionPaletteActions instance)
        {
            @ClosePalette.started -= instance.OnClosePalette;
            @ClosePalette.performed -= instance.OnClosePalette;
            @ClosePalette.canceled -= instance.OnClosePalette;
        }

        public void RemoveCallbacks(IActionPaletteActions instance)
        {
            if (m_Wrapper.m_ActionPaletteActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IActionPaletteActions instance)
        {
            foreach (var item in m_Wrapper.m_ActionPaletteActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ActionPaletteActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ActionPaletteActions @ActionPalette => new ActionPaletteActions(this);
    public interface IRTSCameraActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnMouseMove(InputAction.CallbackContext context);
        void OnMouseZoom(InputAction.CallbackContext context);
    }
    public interface ISelectionActions
    {
        void OnMousePos(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnInclude(InputAction.CallbackContext context);
        void OnExclude(InputAction.CallbackContext context);
        void OnInvertSelect(InputAction.CallbackContext context);
    }
    public interface INumberActions
    {
        void On_1(InputAction.CallbackContext context);
        void On_2(InputAction.CallbackContext context);
        void On_3(InputAction.CallbackContext context);
        void On_4(InputAction.CallbackContext context);
        void On_5(InputAction.CallbackContext context);
        void On_6(InputAction.CallbackContext context);
        void On_7(InputAction.CallbackContext context);
        void On_8(InputAction.CallbackContext context);
        void On_9(InputAction.CallbackContext context);
        void On_0(InputAction.CallbackContext context);
    }
    public interface ICommandActions
    {
        void OnOpenActionPalette(InputAction.CallbackContext context);
    }
    public interface IActionPaletteActions
    {
        void OnClosePalette(InputAction.CallbackContext context);
    }
}
