// This file is auto-generated by AudioPlayList
namespace TFSystem
{
	public partial class AudioPlayList
	{
		public static readonly string Key_TestBGM_Audio_Random_Container_랜덤오디오 = "TestBGM/Audio_Random_Container_랜덤오디오";
		public static readonly string Key_TestBGM_Thaxted = "TestBGM/Thaxted";
	}
}
